name: qccodar
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10, <3.11
  - docopt
  - geopy
  - ipython
  - jupyter
  - matplotlib
  - netcdf4
  - numpy<=2.4.6
  - oceans
  - pandas=2.2.3
  - seawater
  - xarray<=2026.7.0
  - watchdog
  - pip
  - hfradarpy=0.1.5.4
